export const LIST_DOCTORS = [
  {
    id: "doctor-a1b2c3d4e5",
    name: "dr. Andi Setiawan",
    specialization: "Spesialis Jantung",
    email: "andi.setiawan@hospital.com",
    phone: "+6281234567890",
    hospital_name: "RS Harapan Sehat Jakarta",
    hospital_address: "Jl. Sudirman No.45, Jakarta Pusat, DKI Jakarta",
    experience_years: 12,
    workday_start: 1,
    workday_end: 5,
    worktime_start: "09:00:00",
    worktime_end: "14:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  },
  {
    id: "doctor-f9g8h7i6j5",
    name: "dr. Bunga Lestari",
    specialization: "Spesialis Anak",
    email: "bunga.lestari@hospital.com",
    phone: "+6281234567891",
    hospital_name: "RS Anak Bahagia Bandung",
    hospital_address: "Jl. Asia Afrika No.23, Bandung, Jawa Barat",
    experience_years: 8,
    workday_start: 2,
    workday_end: 6,
    worktime_start: "10:00:00",
    worktime_end: "15:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  },
  {
    id: "doctor-k1l2m3n4o5",
    name: "dr. Citra Prameswari",
    specialization: "Spesialis Bedah Umum",
    email: "citra.prameswari@hospital.com",
    phone: "+6281234567892",
    hospital_name: "RS Dermacare Surabaya",
    hospital_address: "Jl. Diponegoro No.77, Surabaya, Jawa Timur",
    experience_years: 10,
    workday_start: 1,
    workday_end: 4,
    worktime_start: "13:00:00",
    worktime_end: "18:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Offline"
  },
  {
    id: "doctor-p9q8r7s6t5",
    name: "dr. Dwi Pratama",
    specialization: "Spesialis Penyakit Dalam",
    email: "dwi.pratama@hospital.com",
    phone: "+6281234567893",
    hospital_name: "RS Mitra Medika Yogyakarta",
    hospital_address: "Jl. Kaliurang Km 5, Sleman, Yogyakarta",
    experience_years: 15,
    workday_start: 1,
    workday_end: 5,
    worktime_start: "08:00:00",
    worktime_end: "13:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  },
  {
    id: "doctor-u1v2w3x4y5",
    name: "dr. Eka Saputra",
    specialization: "Spesialis Bedah Umum",
    email: "eka.saputra@hospital.com",
    phone: "+6281234567894",
    hospital_name: "RS Bedah Mandiri Semarang",
    hospital_address: "Jl. Pandanaran No.88, Semarang, Jawa Tengah",
    experience_years: 11,
    workday_start: 2,
    workday_end: 6,
    worktime_start: "09:00:00",
    worktime_end: "14:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Offline"
  },
  {
    id: "doctor-z9a8b7c6d5",
    name: "dr. Farah Widya",
    specialization: "Spesialis Anak",
    email: "farah.widya@hospital.com",
    phone: "+6281234567895",
    hospital_name: "RS Ibu & Anak Citra Malang",
    hospital_address: "Jl. Ijen No.12, Malang, Jawa Timur",
    experience_years: 9,
    workday_start: 1,
    workday_end: 5,
    worktime_start: "10:00:00",
    worktime_end: "16:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  },
  {
    id: "doctor-e1f2g3h4i5",
    name: "dr. Galih Mahendra",
    specialization: "Spesialis Saraf",
    email: "galih.mahendra@hospital.com",
    phone: "+6281234567896",
    hospital_name: "RS Neuro Center Jakarta",
    hospital_address: "Jl. Gatot Subroto No.120, Jakarta Selatan, DKI Jakarta",
    experience_years: 14,
    workday_start: 1,
    workday_end: 4,
    worktime_start: "08:30:00",
    worktime_end: "13:30:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Offline"
  },
  {
    id: "doctor-j9k8l7m6n5",
    name: "dr. Hana Kartika",
    specialization: "Spesialis Saraf",
    email: "hana.kartika@hospital.com",
    phone: "+6281234567897",
    hospital_name: "RS Mata Nusantara Bandung",
    hospital_address: "Jl. Braga No.9, Bandung, Jawa Barat",
    experience_years: 7,
    workday_start: 3,
    workday_end: 6,
    worktime_start: "11:00:00",
    worktime_end: "16:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Offline"
  },
  {
    id: "doctor-o1p2q3r4s5",
    name: "dr. Indra Kusuma",
    specialization: "Spesialis Jantung",
    email: "indra.kusuma@hospital.com",
    phone: "+6281234567898",
    hospital_name: "RS THT Prima Surabaya",
    hospital_address: "Jl. Raya Darmo No.101, Surabaya, Jawa Timur",
    experience_years: 13,
    workday_start: 1,
    workday_end: 5,
    worktime_start: "09:00:00",
    worktime_end: "13:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  },
  {
    id: "doctor-t9u8v7w6x5",
    name: "dr. Joko Santoso",
    specialization: "Spesialis Penyakit Dalam",
    email: "joko.santoso@hospital.com",
    phone: "+6281234567899",
    hospital_name: "RS Paru Harapan Yogyakarta",
    hospital_address: "Jl. Kusumanegara No.55, Kota Yogyakarta, Yogyakarta",
    experience_years: 10,
    workday_start: 2,
    workday_end: 6,
    worktime_start: "08:00:00",
    worktime_end: "12:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  },
  {
    id: "doctor-y1z2a3b4c5",
    name: "dr. Kartini Ayu",
    specialization: "Spesialis Saraf",
    email: "kartini.ayu@hospital.com",
    phone: "+6281234567800",
    hospital_name: "RS Jiwa Sejahtera Semarang",
    hospital_address: "Jl. Dr. Cipto No.144, Semarang, Jawa Tengah",
    experience_years: 16,
    workday_start: 1,
    workday_end: 4,
    worktime_start: "13:00:00",
    worktime_end: "18:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  },
  {
    id: "doctor-d9e8f7g6h5",
    name: "dr. Leo Prabowo",
    specialization: "Spesialis Bedah Umum",
    email: "leo.prabowo@hospital.com",
    phone: "+6281234567801",
    hospital_name: "RS Ortopedi Solo",
    hospital_address: "Jl. Slamet Riyadi No.321, Surakarta, Jawa Tengah",
    experience_years: 12,
    workday_start: 1,
    workday_end: 5,
    worktime_start: "09:00:00",
    worktime_end: "14:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Offline"
  },
  {
    id: "doctor-i1j2k3l4m5",
    name: "dr. Maria Susanti",
    specialization: "Spesialis Penyakit Dalam",
    email: "maria.susanti@hospital.com",
    phone: "+6281234567802",
    hospital_name: "RS Gizi Sehat Jakarta",
    hospital_address: "Jl. Cikini Raya No.20, Jakarta Pusat, DKI Jakarta",
    experience_years: 6,
    workday_start: 2,
    workday_end: 4,
    worktime_start: "10:00:00",
    worktime_end: "15:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  },
  {
    id: "doctor-n9o8p7q6r5",
    name: "dr. Nanda Wijaya",
    specialization: "Spesialis Anak",
    email: "nanda.wijaya@hospital.com",
    phone: "+6281234567803",
    hospital_name: "Klinik Dental Care Bandung",
    hospital_address: "Jl. Setiabudi No.77, Bandung, Jawa Barat",
    experience_years: 5,
    workday_start: 1,
    workday_end: 6,
    worktime_start: "09:00:00",
    worktime_end: "17:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  },
  {
    id: "doctor-s1t2u3v4w5",
    name: "dr. Olivia Rahma",
    specialization: "Spesialis Bedah Umum",
    email: "olivia.rahma@hospital.com",
    phone: "+6281234567804",
    hospital_name: "RS Rehabilitasi Medika Surabaya",
    hospital_address: "Jl. Mayjen Sungkono No.200, Surabaya, Jawa Timur",
    experience_years: 8,
    workday_start: 1,
    workday_end: 5,
    worktime_start: "08:00:00",
    worktime_end: "13:00:00",
    join_date: "25:47.5",
    update_date: "25:47.5",
    connected: "Online"
  }
];